// BootScene — loads assets and generates placeholder textures.
// Real art (drawn by hand, per jam rules) replaces these during the jam.

// Bump on any asset re-render so returning browsers fetch the new file instead
// of a stale cached copy at the same URL (bit us during dev: the server was
// serving the updated PNG but the browser's image cache kept the old one).
const ASSET_V = 4;

class BootScene extends Phaser.Scene {
  constructor() {
    super('Boot');
  }

  preload() {
    // Loading bar (matters once real assets exist)
    const barW = 320, barH = 8;
    const cx = this.scale.width / 2, cy = this.scale.height / 2;
    const track = this.add.rectangle(cx, cy, barW, barH, 0x333333);
    const fill = this.add.rectangle(cx - barW / 2, cy, 0, barH, 0x007acc).setOrigin(0, 0.5);
    this.load.on('progress', v => { fill.width = barW * v; });

    const img = (key, file) => this.load.image(key, 'assets/' + file + '.png?v=' + ASSET_V);

    // Hand-made art (Blender pixel-art renders, per jam rules — no AI art).
    // Same keys as the code placeholders, so Battle.makeTextures skips them and
    // still applies NEAREST filtering. Generated by blender/gen_backdrops.py.
    // One difficulty backdrop per stage/monster: VERY EASY -> ork ... SURVIVAL -> demon.
    ['ork', 'skeleton', 'elf', 'goblin', 'vampire', 'demon'].forEach(t => {
      img('bg_' + t, 'bg_' + t);        // battle-strip backdrop
      img('scene_' + t, 'scene_' + t);  // full-screen atmosphere
    });
    img('pause_panel', 'pause_panel');   // ESC/pause window
    img('menu_splash', 'menu_splash');   // title-screen key art
    img('title_panel', 'title_panel');   // title-text backing plate

    // characters — Blender-rendered 3D pixel-art figurines (same keys as the
    // code placeholders). hero tiers 0-5 (sword + crossbow 'x') and 6 monsters.
    for (let t = 0; t < 6; t++) {
      img('hero' + t, 'hero' + t);
      img('hero' + t + 'x', 'hero' + t + 'x');
      // second idle frame per tier/weapon (Battle.startIdleAnim swaps at ~4fps)
      img('hero' + t + '_b', 'hero' + t + '_b');
      img('hero' + t + 'x_b', 'hero' + t + 'x_b');
    }
    ['ork', 'skeleton', 'elf', 'goblin', 'vampire', 'demon'].forEach(t => {
      img('en_' + t, 'en_' + t);
      img('en_' + t + '_boss', 'en_' + t + '_boss');  // crowned boss variant
    });

    // loot icons — same keys Items.makeTextures() checks, so it skips its own
    // placeholder once these are loaded. The five gems (prism/sigil/core/shard/
    // vault) come from the same blender/gen_items.py pass as the originals.
    //
    // No ASSET_V bump for the gems: these filenames have never been served, so
    // no browser can be holding a stale copy of them, and bumping would throw
    // away every cached backdrop and character sheet for nothing. Bump it only
    // when an EXISTING asset is re-rendered.
    //
    // If a gem PNG is absent (not rendered yet) the load simply fails, the key
    // never registers, and Items.makeTextures() draws its code placeholder —
    // that is the intended degradation, not a missing-texture bug.
    ['sword', 'armor', 'potion', 'scroll', 'treasure',
     'prism', 'sigil', 'core', 'shard', 'vault'].forEach(t => {
      img('it_' + t, 'it_' + t);
    });
  }

  create() {
    this.makeTextures();
    Battle.makeTextures(this);
    Items.makeTextures(this);
    Items.pruneOld();   // drop stale per-day localStorage keys (see items.js)
    this.scene.start('Menu');
  }

  makeTextures() {
    const g = this.add.graphics();

    // player: 24x24 red square with white core
    g.fillStyle(0xe3242b).fillRect(0, 0, 24, 24);
    g.fillStyle(0xf2f2f2).fillRect(8, 8, 8, 8);
    g.generateTexture('player', 24, 24);
    g.clear();

    // dot: 10x10 white diamond-ish square
    g.fillStyle(0xf2f2f2).fillRect(0, 0, 10, 10);
    g.generateTexture('dot', 10, 10);
    g.clear();

    // pixel: 2x2 white square (particles)
    g.fillStyle(0xffffff).fillRect(0, 0, 2, 2);
    g.generateTexture('pixel', 2, 2);

    g.destroy();
  }
}
