// BootScene — loads assets and generates placeholder textures.
// Real art (drawn by hand, per jam rules) replaces these during the jam.

class BootScene extends Phaser.Scene {
  constructor() {
    super('Boot');
  }

  preload() {
    // Loading bar (matters once real assets exist)
    const barW = 320, barH = 8;
    const cx = this.scale.width / 2, cy = this.scale.height / 2;
    const track = this.add.rectangle(cx, cy, barW, barH, 0x333333);
    const fill = this.add.rectangle(cx - barW / 2, cy, 0, barH, 0x007acc).setOrigin(0, 0.5);
    this.load.on('progress', v => { fill.width = barW * v; });

    // Hand-made art (Blender pixel-art renders, per jam rules — no AI art).
    // Same keys as the code placeholders, so Battle.makeTextures skips them and
    // still applies NEAREST filtering. Generated by blender/gen_backdrops.py.
    // One difficulty backdrop per stage/monster: VERY EASY -> ork ... SURVIVAL -> demon.
    ['ork', 'skeleton', 'elf', 'goblin', 'vampire', 'demon'].forEach(t => {
      this.load.image('bg_' + t, 'assets/bg_' + t + '.png');        // battle-strip backdrop
      this.load.image('scene_' + t, 'assets/scene_' + t + '.png');  // full-screen atmosphere
    });
    this.load.image('pause_panel', 'assets/pause_panel.png');       // ESC/pause window
    this.load.image('menu_splash', 'assets/menu_splash.png');       // title-screen key art

    // characters — Blender-rendered 3D pixel-art figurines (same keys as the
    // code placeholders). hero tiers 0-5 (sword + crossbow 'x') and 6 monsters.
    for (let t = 0; t < 6; t++) {
      this.load.image('hero' + t, 'assets/hero' + t + '.png');
      this.load.image('hero' + t + 'x', 'assets/hero' + t + 'x.png');
    }
    ['ork', 'skeleton', 'elf', 'goblin', 'vampire', 'demon'].forEach(t => {
      this.load.image('en_' + t, 'assets/en_' + t + '.png');
      this.load.image('en_' + t + '_boss', 'assets/en_' + t + '_boss.png');  // crowned boss variant
    });

    // loot icons — same keys Items.makeTextures() checks, so it skips its own
    // placeholder once these are loaded.
    ['sword', 'armor', 'potion', 'scroll', 'treasure'].forEach(t => {
      this.load.image('it_' + t, 'assets/it_' + t + '.png');
    });
  }

  create() {
    this.makeTextures();
    Battle.makeTextures(this);
    Items.makeTextures(this);
    Items.pruneOld();   // drop stale per-day localStorage keys (see items.js)
    this.scene.start('Menu');
  }

  makeTextures() {
    const g = this.add.graphics();

    // player: 24x24 red square with white core
    g.fillStyle(0xe3242b).fillRect(0, 0, 24, 24);
    g.fillStyle(0xf2f2f2).fillRect(8, 8, 8, 8);
    g.generateTexture('player', 24, 24);
    g.clear();

    // dot: 10x10 white diamond-ish square
    g.fillStyle(0xf2f2f2).fillRect(0, 0, 10, 10);
    g.generateTexture('dot', 10, 10);
    g.clear();

    // pixel: 2x2 white square (particles)
    g.fillStyle(0xffffff).fillRect(0, 0, 2, 2);
    g.generateTexture('pixel', 2, 2);

    g.destroy();
  }
}
